[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleVersion = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2024.09.00"
json = "1.8.0"
retrofit = "3.0.0"
gsonConverter = "3.0.0"
coil = "3.2.0"
navigation = "2.9.6"
roomVersion = "2.8.4"
ksp = "2.0.21-1.0.25"
coroutinesTest = "1.10.2"
mockitoCore = "5.21.0"
mockitoKotlin = "6.2.3"
turbine = "1.2.1"
hilt = "2.57.1"
hiltNavigation = "1.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-serialization-json = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "json"}
retrofit-core = {group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-gson-converter = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gsonConverter" }
coil-compose = {group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil"}
coil-network = {group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil"}
androidx-navigation-compose = {group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation"}
androidx-room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
androidx-room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-room-guava = {group = "androidx.room", name = "room-guava", version.ref = "roomVersion" }
kotlinx-coroutine-test = {group = "org.jetbrains.kotlinx", name= "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mockito-core = {group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = {group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
turbine = {group = "app.cash.turbine", name = "turbine", version.ref = "turbine"}
android-hilt = {group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = {group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt"}
androidx-lifecycle-viewmodel-compose = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleVersion"}
androidx-hilt-navigation-compose = {group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation"}


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
dagger-hilt = {id = "com.google.dagger.hilt.android", version.ref = "hilt"}


